//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HireCar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HireCarEntities1 : DbContext
    {
        public HireCarEntities1()
            : base("name=HireCarEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<car> cars { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<rent> rents { get; set; }
        public virtual DbSet<returncar> returncars { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
